### ISSUE TITLE
it have a event when trigger when a new row is ready to be created

### ISSUE THREAD

**Issue by mavelar** [gr2m/editable-table#22]

**Comment by gr2m** [comment]
Does `$table.on('record:add', function (event, record, index) { /* ... */ })` work for you? I just found out that we don’t document it in the README yet, would you send a pull request to add it to the documentation? I’d very much appreciate it :) The events are listed in the source code at https://github.com/gr2m/editable-table/blob/master/editable-table.js#L11-L15

**Comment by mavelar** [comment]
Hi @gr2m, ok I will do that, thanks
