### ISSUE TITLE
Read-only or frozen columns

### ISSUE THREAD

**Issue by manna** [gr2m/editable-table#25]
Hey @gr2m - cool project. Would be very nice to be able to configure some columns as editable and others as read only.

**Comment by gr2m** [comment]
Shouldn't that just work? If you put in text in a cell, it should be copied

**Comment by manna** [comment]
Yeah. I wanted to use editableTable.add to add new read-only rows to the end, while choosing their frozen values. This can be accomplished by adding the `disabled` keyword. e.g.:

<input name="name" placeholder="Joe Doe" autocomplete="off" **disabled**/>

and

editableTable.add({ name: "Joe", email: "joe@example.com" });

**Comment by gr2m** [comment]
Got it. Does that work for you? Can we close the issue?

**Comment by manna** [comment]
That works for me, thanks
