### ISSUE TITLE
adding sort by column and search

### ISSUE THREAD

**Issue by amine-bouassida** [gr2m/editable-table#6]
Hi,
Thank you for this amazing plugin. I opened this issue to suggest two features would be nice to have:
- Clickable table headings that would sort all the data alphabetically according to the clicked column.
- A search field that allows to filter the displayed data.
  If I have time to read your source code and find the good way to implement these features, I will do it soon.

**Comment by gr2m** [comment]
Hey Amine, thanks for the kind words! 

Search & Sort is out of scope for this plugin, but it should be easy to combine it with other plugins, that provide search and/or sort. Could you give that a try first?

**Comment by amine-bouassida** [comment]
Yeah sure. I'll try that first
